//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int sno { get; set; }
        public string location { get; set; }
        public string technology { get; set; }
        public Nullable<int> experience { get; set; }
        public string category { get; set; }
        public string company { get; set; }
    }
}
