//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GraduateDetail
    {
       
        public int gradid { get; set; }
        
        public string firstname { get; set; }
       
        public string lastname { get; set; }
       
        public string gender { get; set; }
        
        public Nullable<System.DateTime> dateofbirth { get; set; }
       
        public string schoolname { get; set; }
       
        public Nullable<int> aggregate1 { get; set; }
        
        public string intercollege { get; set; }
       
        public Nullable<int> aggregate2 { get; set; }
        
        public string graduatecollege { get; set; }
        
        public string branch { get; set; }
       
        public Nullable<int> aggregate3 { get; set; }
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string email { get; set; }
        [Required]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [Phone]
        [Display(Name = "Mobile Number")]
        public string mobilephone { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string password1 { get; set; }
    }
}
